server:
  servlet-path: /swagger
spring:
  application:
    name: spring-document
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    open-in-view: false
swagger:
  butler:
    resources[0]:
      name: service-a
      url: /service-a/v2/api-docs
      swagger-version: 2.0
    resources[1]:
      name: service-b
      url: /service-b/v2/api-docs
      swagger-version: 2.0