spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    open-in-view: false

mybatis:
  type-aliases-package: com.andy.shiro.entity.rbac
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml




