spring:
  application:
    name: seurity
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
security:
  oauth2:
    client:
      client-id: andyid
      client-secret: andysecret
  user:
    name: andy
    password: andy
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
