server:
  port: 8086
  servlet:
    path: /

spring:
  application:
    name: spring-boot-aop
  http:
    encoding:
      charset: UTF-8
      enabled: true
  aop:
    auto: true
    # 需要使用CGLIB来实现AOP的时候配置此属性，默认使用的是标准Java的实现。
    proxy-target-class: true

